### ISSUE TITLE
Support for other libraries (socket.io / deepstream.io / etc)

### ISSUE THREAD

**Issue by lewebsimple** [trailsjs/trailpack-realtime#9]
In the same way Trails.js offers the choice of web server ( Hapi / Express ), should trailpack-realtime become its own Trailpack type (i.e. trailpack/realtime.js) and then be split into trailpack-primus / trailpack-socketio / etc ?

This could be good for standardizing communication with ORM trailpacks, as discussed in #4

**Comment by jaumard** [comment]
Primus can support socket io and some other realtime framework already by modifying the transporter
See https://github.com/primus/primus#supported-real-time-frameworks
